### ISSUE TITLE
caddy.service error INVALIDARGUMENT

### ISSUE THREAD

**Issue by recklessnl** [caddyserver/dist#38]
This is running in an LXC container, only purpose is Caddy, so running as root user.
```
root@caddy:~# systemctl status caddy
* caddy.service - Caddy
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-06-06 14:44:18 CDT; 52s ago
     Docs: https://caddyserver.com/docs/
  Process: 119 ExecStart=/root/caddy run --config /root/Caddyfile2 --adapter caddyfile (code=exited, status=2)
 Main PID: 119 (code=exited, status=2)

Jun 06 14:44:18 caddy caddy[119]:         runtime/proc.go:1041
Jun 06 14:44:18 caddy caddy[119]: goroutine 1 [running]:
Jun 06 14:44:18 caddy caddy[119]: runtime.systemstack_switch()
Jun 06 14:44:18 caddy caddy[119]:         runtime/asm_amd64.s:330 fp=0xc00005e788 sp=0xc00005e780 pc=0x465320
Jun 06 14:44:18 caddy caddy[119]: runtime.main()
Jun 06 14:44:18 caddy caddy[119]:         runtime/proc.go:133 +0x70 fp=0xc00005e7e0 sp=0xc00005e788 pc=0x436c70
Jun 06 14:44:18 caddy caddy[119]: runtime.goexit()
Jun 06 14:44:18 caddy caddy[119]:         runtime/asm_amd64.s:1373 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x4672b1
Jun 06 14:44:18 caddy systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 06 14:44:18 caddy systemd[1]: caddy.service: Failed with result 'exit-code'.
```

This is in `/etc/systemd/system/caddy.service`:
```
[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target

[Service]
ExecStart=/root/caddy run --config /root/Caddyfile2 --adapter caddyfile
ExecReload=/root/caddy reload --config /root/Caddyfile2 --adapter caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

Running the command listed at ExecStart manually after boot works just fine.

Caddyfile:

```
(SecurityHeaders) {
        header {
                Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
                X-Xss-Protection "1; mode=block"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "SAMEORIGIN"
                Content-Security-Policy "upgrade-insecure-requests"
                Referrer-Policy "strict-origin-when-cross-origin"
                Cache-Control "public, max-age=15, must-revalidate"
                Feature-Policy "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'self'; camera 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb 'none'; vr 'none'"
        }
}

sub.some.domain {
        import SecurityHeaders
        file_server
        reverse_proxy 192.168.1.120:6000
        tls {
                dns cloudflare token
        }
}

hi.some.domain {
        import SecurityHeaders
        @excludeDirs {
                not path /local/folder* 
        }
        file_server
        reverse_proxy @excludeDirs 192.168.1.139:8002
        tls {
                dns cloudflare token
        }
}
```

**Comment by Mohammed90** [comment]
Can you share how you're setting up and running the LXC container? From the error message and reading the relevant code in the Go runtime (as per the error, it is yet to call Caddy's main), it isn't able to achieve something with the system stack.


[Line 132-136](https://golang.org/src/runtime/proc.go)
```go

	if GOARCH != "wasm" { // no threads on wasm yet, so no sysmon

		systemstack(func() {

			newm(sysmon, nil)

		})

	}
```

[Line 1031-1041:](https://golang.org/src/runtime/proc.go)
```go
// mstart is the entry-point for new Ms.

//

// This must not split the stack because we may not even have stack

// bounds set up yet.

//

// May run during STW (because it doesn't have a P yet), so write

// barriers are not allowed.

//

//go:nosplit

//go:nowritebarrierrec

func mstart() {
```

**Comment by recklessnl** [comment]
I'm running it as an unpriviliged LXC container on Proxmox 6.2. If I run the same command when SSH'ed in it works just fine though.

**Comment by francislavoie** [comment]
Closing this as inactive.
